name: Lighthouse
# Run check on pull request
on: [pull_request]

jobs:
  score-check:
    runs-on: ubuntu-latest
    steps:        
    - name: Waiting for 200 from Netlify
      uses: probablyup/wait-for-netlify-action@v3.4.0
      id: preview
      with:
        site_id: '7b1b61e1-e7bc-4225-97f6-bc6f4104fec6'
        max_timeout: 120
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

    - uses: actions/setup-node@v3
      with:
        node-version: '18'
  
    - name: Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.12.x
        lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.preview.outputs.url }} || echo "LHCI failed!"
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LIGHTHOUSE_TOKEN }}

#    - name: Run Lighthouse
#      uses: foo-software/lighthouse-check-action@v10.0.0
#      id: lighthouseCheck
#      with:
#        accessToken: ${{ secrets.LIGHTHOUSE_TOKEN }}
#        gitHubAccessToken: ${{secrets.GITHUB_TOKEN}}
#        emulatedFormFactor: 'all'
#        prCommentEnabled: true
#        prCommentSaveOld: false
#        timeout: 5
#        urls: "${{ steps.preview.outputs.url }},${{ steps.preview.outputs.url }}/posts/,${{ steps.preview.outputs.url }}/posts/writing-posts/markdown-syntax/"
